services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - ELASTIC_PASSWORD=$ELASTICSEARCH_PASSWORD
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
      - xpack.ilm.enabled=true
      - xpack.security.enabled=true
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 2048M
    networks:
      - my-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
      - http.host=0.0.0.0
      - xpack.monitoring.elasticsearch.hosts=http://elastic:$ELASTICSEARCH_PASSWORD@elasticsearch:9200
      - xpack.monitoring.enabled=true
    ports:
      - 12202:12201/udp
    configs:
      - source: config_pipelines
        target: /usr/share/logstash/config/pipelines.yml
      - source: config_ilm_policy
        target: /usr/share/logstash/config/ilm_policy.json
      - source: pipeline_logstash
        target: /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - my-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTICSEARCH_PASSWORD
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - my-network

configs:
  config_pipelines:
    file: ./logstash/config/pipelines.yml
  config_ilm_policy:
    file: ./logstash/config/ilm_policy.json
  pipeline_logstash:
    file: ./logstash/pipeline/logstash.conf

networks:
  my-network:
    external: true

volumes:
  elasticsearch_data: